default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: mastery
  username: postgres
  password: postgres

test:
  <<: *default
  database: mastery_test
  username: postgres
  password: postgres

# TODO
#production:
#  <<: *default
